# remote_theme: sylhare/Type-on-Strap 

# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# title: Chicken Breed Recognizer
# description: An image classification API that classifies 20 different types of chicken breeds around the world.

# author: 
#   name: Md. Tasfiq Kamran
remote_theme: raviriley/agency-jekyll-theme

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Chicken Breed Recognizer
description: An image classification API that classifies 20 different types of chicken breeds around the world.

author: 
  name: Md. Tasfiq Kamran