# remote_theme: CloudCannon/hydra-jekyll-template@main
# plugins: 
# - jekyll-remote-theme

title: Chicken Breed Recognizer
description: An image classification API that classifies 20 different types of chicken breeds around the world.
theme: just-the-docs
url: https://tasfiq-k.github.io/chicken-breeds-recognizer/

author: 
  name: Md. Tasfiq Kamran