remote_theme: automatic-app-landing-page

# plugins: 
# - jekyll-remote-theme

title: Chicken Breed Recognizer
description: An image classification API that classifies 20 different types of chicken breeds around the world.

author: 
  name: Md. Tasfiq Kamran