# -*- coding: utf-8 -*-
"""chicken_breed_inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G4gSb4Om2Eo98V0cF703TjSfg9Pm5ZhJ
"""

!pip install -Uqq fastai

from fastai.vision.all import *

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Dataset/chicken_breed_recognizer

version = 2
img_path = 'test_images/'
model_path = f"models/chicken_breed_recognizer-v{version}.pkl"

model = load_learner(model_path)

# get the chicken list

# load the pickle file 
with open("chicken_breeds", "rb") as fp:
    chicken_list = pickle.load(fp)
chicken_list

"""# Inference 1, Ground Truth: (Austra White chicken)"""

img = Image.open(f"{img_path}/test_00.jpg")
img.to_thumb(128, 128)

model.predict(img)

pred, idx, probs = model.predict(img)
dict(zip(chicken_list, map(float, probs)))

"""# Inference 2, Ground truth: Cornish Cross chicken"""

img = Image.open(f"{img_path}/cornish_cross_test_01.jpg")
img.to_thumb(128, 128)

model.predict(img)

pred, idx, probs = model.predict(img)
dict(zip(chicken_list, map(float, probs)))

"""# Inference 3, Ground truth: Cornish Cross chicken"""

img = Image.open(f"{img_path}/cornish_cross_test_02.jpg")
img.to_thumb(128, 128)

model.predict(img)

pred, idx, probs = model.predict(img)
dict(zip(chicken_list, map(float, probs)))

"""# Inference 4, Ground truth: Frizzle chicken"""

img = Image.open(f"{img_path}/frizzle_test_03.jpg")
img.to_thumb(128, 128)

model.predict(img)

pred, idx, probs = model.predict(img)
dict(zip(chicken_list, map(float, probs)))

"""# Inference 5, Ground truth: Frizzle chicken"""

img = Image.open(f"{img_path}/frizzle_test_04.jpg")
img.to_thumb(128, 128)

model.predict(img)

pred, idx, probs = model.predict(img)
dict(zip(chicken_list, map(float, probs)))

"""# Inference 6, Ground truth: Polish chicken"""

img = Image.open(f"{img_path}/polish_test_05.jpg")
img.to_thumb(128, 128)

model.predict(img)

pred, idx, probs = model.predict(img)
dict(zip(chicken_list, map(float, probs)))

"""# Inference 7, Ground truth: Polish chicken"""

img = Image.open(f"{img_path}/polish_test_06.jpg")
img.to_thumb(128, 128)

model.predict(img)

pred, idx, probs = model.predict(img)
dict(zip(chicken_list, map(float, probs)))

"""# Inference 8, Ground truth: Cherry Egger"""

img = Image.open(f"{img_path}/cherry_egger_test_07.jpg")
img.to_thumb(128, 128)

model.predict(img)

pred, idx, probs = model.predict(img)
dict(zip(chicken_list, map(float, probs)))

"""# Inference 9, Ground truth: Easter Egger (Failed)"""

img = Image.open(f"{img_path}/easter_egger_test_08.jpg")
img.to_thumb(128, 128)

model.predict(img)

pred, idx, probs = model.predict(img)
dict(zip(chicken_list, map(float, probs)))

"""# Inference 10, Ground truth: Blue Laced Red Wyandotte"""

img = Image.open(f"{img_path}/blue_laced_red_wyandotte_test_09.jpg")
img.to_thumb(128, 128)

model.predict(img)

pred, idx, probs = model.predict(img)
dict(zip(chicken_list, map(float, probs)))

